version: '3'


services:
  db:
    image: mongo
    ports:
      - 27017:27017
#    networks:
#      - backend

#  client-next:
#    image: eu.gcr.io/mussia8/client-next
##    image: yurikrupnik/client-next
#    build:
#      context: apps/fullstack/client-next
#      dockerfile: Dockerfile
#    container_name: client-next
#    environment:
#      - MONGO_URI=mongodb://db/mussia8
#      - PORT=3340
#    ports:
#      - 3340:3340
#    networks:
#      - backend
#    links:
#      - "db:database"
#    depends_on:
#      - db
#
#  bi-service:
##    image: eu.gcr.io/mussia8/bi-service
#    image: yurikrupni/bi-service
#    build:
#      context: apps/big-data/bi-service
#      dockerfile: Dockerfile
#    container_name: bi-service
#    environment:
#      - MONGO_URI=mongodb://db/mussia8
#      #      - MONGO_URI="$$(shell gcloud secrets versions access latest --secret=MONGO_URI --project=mussia8)"
#      #      - MONGO_URI=$MONGO_URI
##      - PORT=3335
#    ports:
#      - 3000:3333
#
#    healthcheck:
#      test: [ 'CMD', 'curl', '-f', 'http://bi-service/apis/health' ]
#      interval: 30s
#      timeout: 30s
#      retries: 5
#
#    networks:
#      - backend
#    depends_on:
#      - db
  #  db1:
  #    image: mongo
  #    ports:
  #      - 27018:27017
  #  users-db:
  #    image: mongo
  #    ports:
  #      - 27019:27017
  #  users-api:
  #    image: eu.gcr.io/mussia8/users-api
  #    build:
  #      context: apps/fullstack/users-api
  #      dockerfile: Dockerfile
  #    container_name: users-api
  #    environment:
  #      - DB_URL=mongodb://db/mussia8
  #      - PORT=3333
  #    ports:
  #      - 3333:3333
  #  projects-api:
  #    image: eu.gcr.io/mussia8/projects-api
  #    build:
  #      context: apps/fullstack/projects-api
  #      dockerfile: Dockerfile
  #    container_name: projects-api
  #    environment:
  #      - DB_URL=mongodb://db/mussia8
  #      - PORT=3334
  #    ports:
  #      - 3334:3334
  #  go-api:
  #    image: eu.gcr.io/mussia8/go-api
  #    build:
  #      context: apps/core/go-api
  #      dockerfile: Dockerfile
  #    container_name: go-api
  #    environment:
  #      - MONGO_URI=mongodb://db/mussia8
  #      - PORT=3000
  #    ports:
  #      - 3001:3000
  #    depends_on:
  #      - db

  #  event1:
  #    image: eu.gcr.io/mussia8/event1
  #    build:
  #      context: apps/fullstack/event1
  #      dockerfile: Dockerfile
  #    container_name: event1
  #    environment:
  #      - MONGO_URI=mongodb://db1/event1
  #      - PORT=3336
  #    ports:
  #      - 3336:3336
  #    depends_on:
  #      - db1
  #  event2:
  #    image: eu.gcr.io/mussia8/event2
  #    build:
  #      context: apps/fullstack/event2
  #      dockerfile: Dockerfile
  #    container_name: event2
  #    environment:
  #      - MONGO_URI=mongodb://db/event2
  #      - PORT=3337
  #    ports:
  #      - 3337:3337
  #    depends_on:
  #      - db
  #  event3:
  #    image: eu.gcr.io/mussia8/event3
  #    build:
  #      context: apps/fullstack/event3
  #      dockerfile: Dockerfile
  #    container_name: event2
  #    environment:
  #      - MONGO_URI=mongodb://db/event3
  #      - PORT=3338
  #    ports:
  #      - 3338:3338
  #    depends_on:
  #      - db
  #  #    command: npm run start
  #  users:
  #    image: eu.gcr.io/mussia8/users
  #    build:
  #      context: apps/fullstack/users
  #      dockerfile: Dockerfile
  #    container_name: users
  #    environment:
  #      - MONGO_URI=mongodb://db/mussia8
  #      - PORT=3339
  #    ports:
  #      - 3339:3339
  #    depends_on:
  #      - db


networks:
  frontend:
    # Use a custom driver
    driver: bridge
  backend:
    # Use a custom driver which takes special options
    driver: bridge

