version: "3"

services:
  lerna:
    image: yurikrupnik/mussia14-builder
    build:
      context: .
    container_name: mussia14-builder
#    volumes:
#      - ./apps/:/app/apps
#      - ./libs/:/app/libs
    deploy:
      replicas: 0
