name: Pulumi
on:
  push:
    branches:
      - main
  pull_request:
#    branches:
#      - main
#    paths:
#      - "apps/big-data/**"
#  pull_request:
#    paths:
#      - "apps/big-data/**"
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: mussia14
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
      - run: |-
          gcloud --quiet auth configure-docker
      - run: pulumi plugin install resource gcp v6.2.0
#      - run: echo this is  ${GOOGLE_APPLICATION_CREDENTIALS}
      - run: export GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
#      - run: echo this is  ${GOOGLE_APPLICATION_CREDENTIAL
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: apps/big-data/infrastructure
#          credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
#          cwd: app/big-data/infra6
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: "''"
