name: Push test
on: push


env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: c-hive/gha-npm-cache@v1
#      - run: npm ci

      - run: git config --global user.email krupnik.yuri@gmail.com && git config --global user.name yurikrupnik
      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc

      - run: gcloud config list
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - run: echo ${{ steps.extract_branch.outputs.branch }}
#      - name: Test Vars
#        env:
#          GH: "${{ github.head_ref }}"
#          GHA: ${{ github.head_ref }}
#          GHH: github.head_ref
#          BRA: ${{ steps.extract_branch.outputs.branch }}
#        run: bash scripts/bash-test.sh
#      - run: echo ${HEAD_REF}
#      - run: echo "${{ github.head_ref }}"
#        todo pass env vars from command to next
#            echo "It's there!"
#          fi
